_core:
  default_config_hash: AKaOOvJLdUkliE4Pd3O_SJznkKMkdNbVL0Gqmry1tXs
langcode: el
admin_css: true
nojs:
  lazy: '0'
  classlist: '0'
  polyfill: '0'
  promise: '0'
  raf: '0'
fx: ''
noscript: false
one_pixel: true
placeholder: ''
unstyled_extensions: ''
responsive_image: false
blazy:
  loadInvisible: false
  offset: 100
  saveViewportOffsetDelay: 50
  validateDelay: 25
  container: ''
io:
  unblazy: false
  rootMargin: 0px
  threshold: '0'
  disconnect: false
extras: {  }
