entity_type_groups:
  node:
    article:
      basic: basic
    page:
      basic: basic
    useful_links:
      basic: basic
  taxonomy_term:
    arthra:
      basic: basic
tag_trim_method: beforeValue
tag_trim_maxlength:
  metatag_maxlength_title: 60
  metatag_maxlength_abstract: null
  metatag_maxlength_description: null
tag_scroll_max_height: ''
